# **Introduction to Numpy**


NumPy (Numerical Python) is a fundamental library in Python for scientific computing. It provides support for multidimensional arrays and matrices, as well as a variety of mathematical functions to operate on these arrays. NumPy is widely used for tasks such as numerical simulations, data analysis, and machine learning.

In [ ]:
import numpy as np

# Creating a NumPy array from a Python list
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Creating a 2D NumPy array (matrix)
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Creating an array of zeros
zeros = np.zeros((3, 3))

# Creating an array of ones
ones = np.ones((2, 4))

# Creating an identity matrix
identity_matrix = np.eye(5)

In [ ]:
# We can perform some numeric mathematical operations on each of the elements in the array.

# Addition
update = arr + 10  # Adds 10 to each element

# Multiplication
update1 = arr * 2   # Multiplies each element by 2

# Element-wise operations between two arrays
update2 = arr + arr

In [ ]:
identity_matrix*5

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

In [ ]:
# Access an element
element = arr[2]   # Access the 3rd element (index 2)

# Slice an array
slice = arr[1:4]   # Get elements from index 1 to 3 (inclusive)

In [ ]:
slice

array([2, 3, 4])

In [ ]:
# Get the shape of an array
shape = arr.shape

# Reshape an array
reshaped = arr.reshape(2, 5)  # Reshape a 1D array to a 2x5 matrix

In [ ]:
reshaped

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
# Doing some aggregation function

# Calculate the mean, median and Standard deviation
mean = np.mean(arr)
median = np.median(arr)  # Median
std_dev = np.std(arr)  # SD

# Calculate the sum
total = np.sum(arr)

# Find the maximum and minimum values
max_val = np.max(arr)
min_val = np.min(arr)

In [ ]:
std_dev

2.8722813232690143

In [ ]:
# Generate an array of random integers between 1 and 100
random_integers = np.random.randint(1, 101, size=15)
random_integers

array([43, 22, 38, 83, 38, 47, 79, 40, 67, 39, 65, 13, 42, 86, 15])

# **Introduction to Pandas**


pandas is an open source library providing high-performance, easy-to-use data structures and data analysis tools for the Python programming language.

Dataset Reference: https://archive.ics.uci.edu/ml/datasets/Bank+Marketing

In [ ]:
# Importing the pandas library
import pandas as pd

DataFrame is a main object in pandas. It is used to represent data with rows and columns like a matrix.

DataFrame is a data-structure that represents the data in tabular or excel spreadsheet like data.

**1. Create a dataFrame "bank_data" from the dataset csv file.**

In [ ]:
# Reading the df_dataset
bank_data = pd.read_csv('bank-full.csv', sep=';')

In [ ]:
# Dimensions of the dataframe

bank_data.shape   # total number of rows and columns

(45211, 17)

In [ ]:
bank_data.columns   # printing column names of a dataframe/table

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'y'],
      dtype='object')

**2. Print the rows of the bank_data df_dataframe**

In [ ]:
# bank_data.tail()  # Printing the last 5 rows of bank_data
# bank_data.head()  # Printing the first 5 rows of bank_data
bank_data.head(3)  # Printing the first n (Eg. n = 3) rows of bank_data
# slicing [start:end]
# bank_data[200:250]

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no

**3. Display a summary statistics of the dataframe.**

In [ ]:
# bank_data.info()
bank_data.describe()  # Displaying the descriptive statistics

,age,balance,day,duration,campaign,pdays,previous
count,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000
mean,40.936210,1362.272058,15.806419,258.163080,2.763841,40.197828,0.580323
std,10.618762,3044.765829,8.322476,257.527812,3.098021,100.128746,2.303441
min,18.000000,-8019.000000,1.000000,0.000000,1.000000,-1.000000,0.000000
25%,33.000000,72.000000,8.000000,103.000000,1.000000,-1.000000,0.000000
50%,39.000000,448.000000,16.000000,180.000000,2.000000,-1.000000,0.000000
75%,48.000000,1428.000000,21.000000,319.000000,3.000000,-1.000000,0.000000
max,95.000000,102127.000000,31.000000,4918.000000,63.000000,871.000000,275.000000

**4. Access and Print all the rows with only 'balance', 'job' and 'age' columns from the df_dataframe**

In [ ]:
# Accessing column
bank_data['job']

0          management
1          technician
2        entrepreneur
3         blue-collar
4             unknown
             ...
45206      technician
45207         retired
45208         retired
45209     blue-collar
45210    entrepreneur
Name: job, Length: 45211, dtype: object

In [ ]:
# Getting two or more columns
col_list = ['age', 'job', 'balance']
bank_data[col_list]

       age           job  balance
0       58    management     2143
1       44    technician       29
2       33  entrepreneur        2
3       47   blue-collar     1506
4       33       unknown        1
...    ...           ...      ...
45206   51    technician      825
45207   71       retired     1729
45208   72       retired     5715
45209   57   blue-collar      668
45210   37  entrepreneur     2971

[45211 rows x 3 columns]

**5. Selecting rows and columns using index locator**

In [ ]:
bank_data.iloc[2]

age                    33
job          entrepreneur
marital           married
education       secondary
default                no
balance                 2
housing               yes
loan                  yes
contact           unknown
day                     5
month                 may
duration               76
campaign                1
pdays                  -1
previous                0
poutcome          unknown
y                      no
Name: 2, dtype: object

In [ ]:
# Select [1, 5, 10] rows and in columns ['age','balance']
bank_data.iloc[[1,5,10]][['age', 'job', 'balance']]

    age         job  balance
1    44  technician       29
5    35  management      231
10   41      admin.      270

**6. Filter the rows where age is greater than 50**

In [ ]:
bank_data[bank_data['age'] > 50]

# bank_data[bank_data['job'] == 'technician']
# bank_data[bank_data['marital'] == 'married']

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
8,58,retired,married,primary,no,121,yes,no,unknown,5,may,50,1,-1,0,unknown,no
12,53,technician,married,secondary,no,6,yes,no,unknown,5,may,517,1,-1,0,unknown,no
13,58,technician,married,unknown,no,71,yes,no,unknown,5,may,71,1,-1,0,unknown,no
14,57,services,married,secondary,no,162,yes,no,unknown,5,may,174,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45204,73,retired,married,secondary,no,2850,no,no,cellular,17,nov,300,1,40,8,failure,yes
45206,51,technician,married,tertiary,no,825,no,no,cellular,17,nov,977,3,-1,0,unknown,yes
45207,71,retired,divorced,primary,no,1729,no,no,cellular,17,nov,456,2,-1,0,unknown,yes
45208,72,retired,married,secondary,no,5715,no,no,cellular,17,nov,1127,5,184,3,success,yes
45209,57,blue-collar,married,secondary,no,668,no,no,telephone,17,nov,508,4,-1,0,unknown,no

**7. Filter the rows where the job is "technician" and the marital status is "married"**

In [ ]:
bank_data[(bank_data['job']=='technician') & (bank_data['marital'] == 'married')]

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
12,53,technician,married,secondary,no,6,yes,no,unknown,5,may,517,1,-1,0,unknown,no
13,58,technician,married,unknown,no,71,yes,no,unknown,5,may,71,1,-1,0,unknown,no
30,57,technician,married,secondary,no,839,no,yes,unknown,5,may,225,1,-1,0,unknown,no
37,53,technician,married,secondary,no,-3,no,no,unknown,5,may,1666,1,-1,0,unknown,no
47,44,technician,married,secondary,no,0,yes,no,unknown,5,may,225,2,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45165,33,technician,married,tertiary,no,2976,yes,no,cellular,9,nov,465,2,95,12,other,no
45179,34,technician,married,secondary,no,1026,no,no,cellular,12,nov,319,1,100,6,failure,no
45182,34,technician,married,secondary,no,133,no,no,cellular,15,nov,401,2,187,5,success,yes
45200,38,technician,married,secondary,no,557,yes,no,cellular,16,nov,1556,4,-1,0,unknown,yes
45206,51,technician,married,tertiary,no,825,no,no,cellular,17,nov,977,3,-1,0,unknown,yes

**8. Calculate the mean age for each different job in the dataframe.**

Pandas dataframe.groupby() function is used to split the data into groups based on some criteria and perform computations for better analysis.

In [ ]:
bank_data.groupby('job')['age'].mean()

job
admin.           39.289886
blue-collar      40.044081
entrepreneur     42.190989
housemaid        46.415323
management       40.449567
retired          61.626767
self-employed    40.484484
services         38.740250
student          26.542644
technician       39.314598
unemployed       40.961627
unknown          47.593750
Name: age, dtype: float64

**9. Find the number of each type of job in the dataframe (Counts)**

In [ ]:
bank_data['job'].value_counts()

#df_data['marital'].value_counts()
#df_data['month'].value_counts()

blue-collar      9732
management       9458
technician       7597
admin.           5171
services         4154
retired          2264
self-employed    1579
entrepreneur     1487
unemployed       1303
housemaid        1240
student           938
unknown           288
Name: job, dtype: int64

**10. Sort df_dataframe first by the values in the 'age' in a decending order**

In [ ]:
bank_data.sort_values('age',ascending=False)

#bank_data.sort_values('age',ascending=True)

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
41663,95,retired,married,secondary,no,0,no,no,telephone,1,oct,215,1,-1,0,unknown,no
33699,95,retired,divorced,primary,no,2282,no,no,telephone,21,apr,207,17,-1,0,unknown,yes
31233,94,retired,divorced,secondary,no,1234,no,no,cellular,3,mar,212,1,-1,0,unknown,no
44420,93,retired,married,unknown,no,775,no,no,cellular,4,aug,476,2,13,9,success,yes
44262,93,retired,married,unknown,no,775,no,no,cellular,22,jul,860,2,177,7,success,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41222,18,student,single,unknown,no,35,no,no,telephone,21,aug,104,2,-1,0,unknown,no
42146,18,student,single,secondary,no,156,no,no,cellular,4,nov,298,2,82,4,other,no
41252,18,student,single,secondary,no,5,no,no,cellular,24,aug,143,2,-1,0,unknown,no
42274,18,student,single,primary,no,608,no,no,cellular,13,nov,210,1,93,1,success,yes
41487,18,student,single,unknown,no,108,no,no,cellular,8,sep,169,1,-1,0,unknown,yes

**11. Create a column "decision" with 1 when the balance value > 2000 and 0 when the value < 2000**

In [ ]:
def new_function(x):
    if x > 2000:
        return 1
    else:
        return 0

Pandas DataFrame apply() function is used to apply a function along an axis of the DataFrame.

In [ ]:
bank_data["decision"]=bank_data["balance"].apply(new_function)
bank_data.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y,decision
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no,1
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no,0
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no,0
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no,0
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no,0

For more practice on other pandas built-in functions, please refer the following resources:


[1] https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf


[2] https://pandas.pydata.org/docs/reference/index.html